# Generated by Django 4.1.1 on 2022-09-24 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1, verbose_name='Estado civil')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('razao_social', models.CharField(max_length=150)),
                ('cnpj', models.CharField(help_text='XX.XXX.XXX/0001-XX', max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone celular')),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Nº telefone fixo')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('estoque_minimo', models.IntegerField()),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.produto')),
            ],
        ),
    ]
